title: RJ Aca-ac
logo: assets/img/my_dp.png
description:
  Hello! I am a third-year Computer Science student at La Salle University. I hold professional certificates, gaining hands-on experience in data manipulation, analysis, and machine learning, using tools like Python and SQL. My goal is to empower your business with impactful data solutions. Let us connect and transform your data into your most valuable asset!
theme: jekyll-theme-minimal
