title: RJ Aca-ac
logo: assets/img/my_dp.png
description:
  Hello! I am RJ Aca-ac, a third-year Computer Science student at La Salle University. Alongside my studies, I have earned professional certificates in Data Analytics and Data Science from IBM. These certifications equipped me with practical experience in data manipulation, analysis, visualization, and machine learning, using tools like Python and SQL. My goal is to empower your business with data-driven solutions that are both effective and scalable. Let us connect and explore how can we transform your data into your most valuable asset!
theme: jekyll-theme-minimal
