title: RJ Aca-ac
logo: assets/img/my_dp.png
description:
  Hello! I'm a third-year Computer Science student at La Salle University. I hold professional certificates, gaining experience in data collection, manipulation, analysis, and machine learning. My goal is to empower your business with impactful data solutions. Let's connect and transform your data into your most valuable asset!
theme: jekyll-theme-minimal
